// src/src/app/components/introduccion/introduccion.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-introduccion',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './introduccion.component.html',
  styleUrls: ['./introduccion.component.css']
})
export class IntroduccionComponent {
  heroImage = 'https://images.unsplash.com/photo-1635991062422-b3e2f8c36dce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbmRpZ2Vub3VzJTIwY29tbXVuaXR5JTIwY29sb21iaWElMjBtb3VudGFpbnN8ZW58MXx8fHwxNzYzNzQ0MTg0fDA&ixlib=rb-4.1.0&q=80&w=1080';
  eldersImage = 'https://images.unsplash.com/photo-1665708468457-08c52d98cada?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbmRpZ2Vub3VzJTIwZWxkZXJzJTIwd2lzZG9tfGVufDF8fHx8MTc2Mzc0NDE4NHww&ixlib=rb-4.1.0&q=80&w=1080';
}

<div class="space-y-8">
  <!-- Hero Image -->
  <div class="rounded-lg overflow-hidden shadow-lg">
    <img
      [src]="heroImage"
      alt="Paisaje del Resguardo Indígena La Gaitana"
      class="w-full h-64 md:h-96 object-cover"
    />
  </div>

  <!-- Title Section -->
  <div class="text-center space-y-4">
    <h2 class="text-orange-800">NUESTRA IDENTIDAD NASA</h2>
    <h3 class="text-amber-700">Resguardo Indígena La Gaitana</h3>
    <p class="text-orange-700">Vereda El Lago, Inzá - Cauca</p>
  </div>

  <!-- Quote -->
  <div class="bg-gradient-to-r from-orange-50 to-amber-50 p-6 rounded-lg border-l-4 border-orange-700 shadow-md">
    <p class="text-center italic text-orange-900">
      "Los ancianos son bibliotecas vivientes, caminantes de la memoria"
    </p>
  </div>

  <!-- Elders Image -->
  <div class="rounded-lg overflow-hidden shadow-lg">
    <img
      [src]="eldersImage"
      alt="Mayores de la comunidad"
      class="w-full h-64 md:h-80 object-cover"
    />
  </div>

  <!-- History Section -->
  <div class="space-y-4">
    <h3 class="text-orange-800">Historia de Nuestro Territorio</h3>
    
    <div class="bg-orange-50 p-6 rounded-lg">
      <h4 class="text-orange-700 mb-3">Antiguo territorio ancestral: el pueblo Guanaco</h4>
      <p class="text-gray-700 leading-relaxed">
        El resguardo La Gaitana se encuentra ubicado sobre el territorio ancestral Guanaco, 
        pues la comunidad actual reconoce que desciende del antiguo pueblo Guanaco, hoy desaparecido.
      </p>
    </div>
  </div>

  <!-- Objective -->
  <div class="bg-gradient-to-r from-orange-700 to-amber-600 text-white p-8 rounded-lg shadow-lg">
    <div class="flex items-start gap-4">
      <svg class="w-8 h-8 flex-shrink-0 mt-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path>
      </svg>
      <div>
        <h4 class="mb-3">Objetivo de esta cartilla:</h4>
        <p class="leading-relaxed">
          Preservar y compartir los conocimientos ancestrales a través de formatos digitales accesibles.
        </p>
      </div>
    </div>
  </div>
</div>

// src/components/Introduccion.tsx
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { BookOpen } from "lucide-react";

export function Introduccion() {
  return (
    <div className="space-y-8">
      {/* Hero Image */}
      <div className="rounded-lg overflow-hidden shadow-lg">
        <ImageWithFallback
          src=".\public\img\unnamed.jpg"
          alt="Paisaje del Resguardo Indígena La Gaitana"
          className="w-full h-64 md:h-96 object-cover"
        />
      </div>

      {/* Title Section */}
      <div className="text-center space-y-4">
        <h2 className="text-orange-800">NUESTRA IDENTIDAD NASA</h2>
        <h3 className="text-amber-700">Resguardo Indígena La Gaitana</h3>
        <p className="text-orange-700">Vereda El Lago, Inzá - Cauca</p>
      </div>

      {/* Quote */}
      <div className="bg-gradient-to-r from-orange-50 to-amber-50 p-6 rounded-lg border-l-4 border-orange-700 shadow-md">
        <p className="text-center italic text-orange-900">
          "Los mayores y mayoras son bibliotecas vivientes, caminantes de la memoria"
        </p>
      </div>

      {/* Elders Image */}
      <div className="rounded-lg overflow-hidden shadow-lg">
        <ImageWithFallback
          src="https://images.unsplash.com/photo-1665708468457-08c52d98cada?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbmRpZ2Vub3VzJTIwZWxkZXJzJTIwd2lzZG9tfGVufDF8fHx8MTc2Mzc0NDE4NHww&ixlib=rb-4.1.0&q=80&w=1080"
          alt="Mayores de la comunidad"
          className="w-full h-64 md:h-80 object-cover"
        />
      </div>

      {/* History Section */}
      <div className="space-y-4">
        <h3 className="text-orange-800">Historia de Nuestro Territorio</h3>

        <div className="bg-orange-50 p-6 rounded-lg">
          <h4 className="text-orange-700 mb-3">Antiguo territorio ancestral: el pueblo Guanaco</h4>
          <p className="text-gray-700 leading-relaxed">
            El resguardo La Gaitana se encuentra ubicado sobre el territorio ancestral Guanaco,
            pues la comunidad actual reconoce que desciende del antiguo pueblo Guanaco, hoy desaparecido.
          </p>
        </div>
      </div>

      {/* Objective */}
      <div className="bg-gradient-to-r from-orange-700 to-amber-600 text-white p-8 rounded-lg shadow-lg">
        <div className="flex items-start gap-4">
          <BookOpen className="size-8 flex-shrink-0 mt-1" />
          <div>
            <h4 className="mb-3">Objetivo de esta cartilla:</h4>
            <p className="leading-relaxed">
              Preservar y compartir los conocimientos ancestrales a través de formatos digitales accesibles.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
