// src/src/app/components/origen-nasa/origen-nasa.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-origen-nasa',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './origen-nasa.component.html',
  styleUrls: ['./origen-nasa.component.css']
})
export class OrigenNasaComponent {
  heroImage = 'https://images.unsplash.com/photo-1587490693792-52d6b2d9b191?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3VudGFpbiUyMGxhbmRzY2FwZSUyMGNvbG9tYmlhfGVufDF8fHx8MTc2Mzc0NDE4NXww&ixlib=rb-4.1.0&q=80&w=1080';
  
  pueblos = ['Guanacos', 'Misak', 'Coconucos', 'Puracé'];
}

<div class="space-y-8">
  <div class="text-center mb-6">
    <div class="flex justify-center mb-4">
      <svg class="w-16 h-16 text-orange-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"></path>
      </svg>
    </div>
    <h2 class="text-orange-800">ORIGEN DEL PUEBLO NASA</h2>
  </div>

  <!-- Hero Image -->
  <div class="rounded-lg overflow-hidden shadow-lg">
    <img
      [src]="heroImage"
      alt="Territorio ancestral Nasa"
      class="w-full h-64 md:h-80 object-cover"
    />
  </div>

  <p class="text-gray-700 leading-relaxed">
    El pueblo Nasa —también llamados "paeces"— es uno de los pueblos indígenas más antiguos del Cauca y Tierradentro.
  </p>

  <!-- Section 1: Origen Mítico -->
  <div class="bg-gradient-to-br from-orange-50 to-amber-50 p-6 rounded-lg shadow-md">
    <div class="flex items-center gap-3 mb-4">
      <div class="bg-orange-700 text-white rounded-full w-12 h-12 flex items-center justify-center flex-shrink-0">
        <span>1</span>
      </div>
      <h3 class="text-orange-800">Origen mítico</h3>
    </div>
    
    <p class="text-gray-700 mb-4">
      La cosmogonía nasa relata que el pueblo nació de la unión entre:
    </p>
    
    <div class="space-y-3 ml-6">
      <div class="flex items-center gap-3">
        <div class="w-2 h-2 bg-orange-700 rounded-full"></div>
        <p class="text-gray-700"><strong>Uma</strong> (la tierra)</p>
      </div>
      <div class="flex items-center gap-3">
        <div class="w-2 h-2 bg-orange-700 rounded-full"></div>
        <p class="text-gray-700"><strong>Tay</strong> (el sol)</p>
      </div>
      <div class="flex items-center gap-3">
        <div class="w-2 h-2 bg-orange-700 rounded-full"></div>
        <p class="text-gray-700">y la <strong>estrella</strong>, que tocó una laguna sagrada dando origen a los primeros Nasa.</p>
      </div>
    </div>
  </div>

  <!-- Section 2: Ubicación -->
  <div class="bg-gradient-to-br from-orange-50 to-amber-50 p-6 rounded-lg shadow-md">
    <div class="flex items-center gap-3 mb-4">
      <div class="bg-orange-700 text-white rounded-full w-12 h-12 flex items-center justify-center flex-shrink-0">
        <span>2</span>
      </div>
      <h3 class="text-orange-800">Ubicación ancestral</h3>
    </div>
    
    <p class="text-gray-700">
      Los Nasa han habitado históricamente la zona occidental y oriental de la cordillera central, 
      especialmente en Inzá y Páez.
    </p>
  </div>

  <!-- Section 3: Luchas -->
  <div class="bg-gradient-to-br from-orange-50 to-amber-50 p-6 rounded-lg shadow-md">
    <div class="flex items-center gap-3 mb-4">
      <div class="bg-orange-700 text-white rounded-full w-12 h-12 flex items-center justify-center flex-shrink-0">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path>
        </svg>
      </div>
      <h3 class="text-orange-800">Luchas históricas</h3>
    </div>
    
    <p class="text-gray-700 mb-3">Los Nasa participaron en:</p>
    
    <div class="space-y-3 ml-6">
      <div class="flex items-start gap-3">
        <div class="w-2 h-2 bg-orange-700 rounded-full mt-2"></div>
        <p class="text-gray-700">Resistencia a la conquista española (1530–1650)</p>
      </div>
      <div class="flex items-start gap-3">
        <div class="w-2 h-2 bg-orange-700 rounded-full mt-2"></div>
        <p class="text-gray-700">Defensa conjunta con los caciques Tálaga, Páez, Taravira, Suyn y Esmisa</p>
      </div>
    </div>
  </div>

  <!-- Section 4: La Gaitana -->
  <div class="bg-gradient-to-br from-orange-50 to-amber-50 p-6 rounded-lg shadow-md">
    <div class="flex items-center gap-3 mb-4">
      <div class="bg-orange-700 text-white rounded-full w-12 h-12 flex items-center justify-center flex-shrink-0">
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd"></path>
        </svg>
      </div>
      <h3 class="text-orange-800">Relación con La Gaitana</h3>
    </div>
    
    <p class="text-gray-700 mb-4">
      La comunidad del resguardo La Gaitana se autoidentifica como Nasa, aunque reconoce raíces y mezcla con:
    </p>
    
    <div class="grid grid-cols-2 md:grid-cols-3 gap-3 mb-4">
      <div *ngFor="let pueblo of pueblos" class="bg-white p-3 rounded-lg text-center shadow-sm">
        <p class="text-orange-700">{{pueblo}}</p>
      </div>
    </div>
    
    <p class="text-gray-700">
      Hoy el resguardo hace parte del CRIC y mantiene lengua Nasa Yuwe, bastón de mando y prácticas tradicionales.
    </p>
  </div>
</div>

// src/components/OrigenNasa.tsx
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { Mountain, Users, Shield, Heart } from "lucide-react";

export function OrigenNasa() {
  return (
    <div className="space-y-8">
      <div className="text-center mb-6">
        <div className="flex justify-center mb-4">
          <Mountain className="size-16 text-orange-700" />
        </div>
        <h2 className="text-orange-800">ORIGEN DEL PUEBLO NASA</h2>
      </div>

      {/* Hero Image */}
      <div className="rounded-lg overflow-hidden shadow-lg">
        <ImageWithFallback
          src="https://images.unsplash.com/photo-1587490693792-52d6b2d9b191?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3VudGFpbiUyMGxhbmRzY2FwZSUyMGNvbG9tYmlhfGVufDF8fHx8MTc2Mzc0NDE4NXww&ixlib=rb-4.1.0&q=80&w=1080"
          alt="Territorio ancestral Nasa"
          className="w-full h-64 md:h-80 object-cover"
        />
      </div>

      <p className="text-gray-700 leading-relaxed">
        El pueblo Nasa —también llamados "paeces"— es uno de los pueblos indígenas más antiguos del Cauca y Tierradentro.
      </p>

      {/* Section 1: Origen Mítico */}
      <div className="bg-gradient-to-br from-orange-50 to-amber-50 p-6 rounded-lg shadow-md">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-orange-700 text-white p-3 rounded-full">
            <span>1</span>
          </div>
          <h3 className="text-orange-800">Origen mítico</h3>
        </div>
        
        <p className="text-gray-700 mb-4">
          La cosmogonía nasa relata que el pueblo nació de la unión entre:
        </p>
        
        <div className="space-y-3 ml-6">
          <div className="flex items-center gap-3">
            <div className="w-2 h-2 bg-orange-700 rounded-full"></div>
            <p className="text-gray-700"><strong>Uma</strong> (la tierra)</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-2 h-2 bg-orange-700 rounded-full"></div>
            <p className="text-gray-700"><strong>Tay</strong> (el sol)</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-2 h-2 bg-orange-700 rounded-full"></div>
            <p className="text-gray-700">y la <strong>estrella</strong>, que tocó una laguna sagrada dando origen a los primeros Nasa.</p>
          </div>
        </div>
      </div>

      {/* Section 2: Ubicación */}
      <div className="bg-gradient-to-br from-orange-50 to-amber-50 p-6 rounded-lg shadow-md">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-orange-700 text-white p-3 rounded-full">
            <span>2</span>
          </div>
          <h3 className="text-orange-800">Ubicación ancestral</h3>
        </div>
        
        <p className="text-gray-700">
          Los Nasa han habitado históricamente la zona occidental y oriental de la cordillera central, 
          especialmente en Inzá y Páez.
        </p>
      </div>

      {/* Section 3: Luchas */}
      <div className="bg-gradient-to-br from-orange-50 to-amber-50 p-6 rounded-lg shadow-md">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-orange-700 text-white p-3 rounded-full">
            <Shield className="size-5" />
          </div>
          <h3 className="text-orange-800">Luchas históricas</h3>
        </div>
        
        <p className="text-gray-700 mb-3">Los Nasa participaron en:</p>
        
        <div className="space-y-3 ml-6">
          <div className="flex items-start gap-3">
            <div className="w-2 h-2 bg-orange-700 rounded-full mt-2"></div>
            <p className="text-gray-700">Resistencia a la conquista española (1530–1650)</p>
          </div>
          <div className="flex items-start gap-3">
            <div className="w-2 h-2 bg-orange-700 rounded-full mt-2"></div>
            <p className="text-gray-700">Defensa conjunta con los caciques Tálaga, Páez, Taravira, Suyn y Esmisa</p>
          </div>
        </div>
      </div>

      {/* Section 4: La Gaitana */}
      <div className="bg-gradient-to-br from-orange-50 to-amber-50 p-6 rounded-lg shadow-md">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-orange-700 text-white p-3 rounded-full">
            <Heart className="size-5" />
          </div>
          <h3 className="text-orange-800">Relación con La Gaitana</h3>
        </div>
        
        <p className="text-gray-700 mb-4">
          La comunidad del resguardo La Gaitana se autoidentifica como Nasa, aunque reconoce raíces y mezcla con:
        </p>
        
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-4">
          <div className="bg-white p-3 rounded-lg text-center shadow-sm">
            <p className="text-orange-700">Guanacos</p>
          </div>
          <div className="bg-white p-3 rounded-lg text-center shadow-sm">
            <p className="text-orange-700">Misak</p>
          </div>
          <div className="bg-white p-3 rounded-lg text-center shadow-sm">
            <p className="text-orange-700">Coconucos</p>
          </div>
          <div className="bg-white p-3 rounded-lg text-center shadow-sm">
            <p className="text-orange-700">Puracé</p>
          </div>
        </div>
        
        <p className="text-gray-700">
          Hoy el resguardo hace parte del CRIC y mantiene lengua Nasa Yuwe, bastón de mando y prácticas tradicionales.
        </p>
      </div>
    </div>
  );
}
